import { Inter, Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <main>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </main>
      </body>
    </html>
  );
}
